### ISSUE TITLE
Rename Quarkus NodeJs?

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-quinoa#564]
Just to remove confusion over what this plug-in is and what it's for compares to Web Bundler etc. most plugins are named for what they do except this one.  Any thought to renaming it Quarkus Node or Quarkus NodeJs ??

As an example the tagline...
> Quinoa is a Quarkus extension which eases the development, the build and serving of single page apps (built with NodeJS: React, Angular, …) alongside Quarkus . It is possible to use it with a Quarkus backend in a single project

Could become...

> Quarkus NodeJs eases the development, the build and serving of single page apps. It is possible to use it with a Quarkus backend in a single project

**Comment by holly-cummins** [comment]
Two thoughts: 

- I agree self-explanatory names are a good thing, but I think Quinoa has a reasonable degree of brand recognition/usage at this stage, so a rename might do more harm than good to adoption.
- I'm also not sure what the right name is. As discussed in #667, Node Js is a back end framework, so people might not be able to work out what Quinoa does from a "Quarkus Node JS" name; one reasonable interpretation is that it transpiles back-end Javascript to back-end Java. You could do the same transform as in #667 and try "Quarkus NPM", but I don't think that really works, because then it sounds like it's a dependency management tool. "Quarkus NPM-compatible" doesn't even sound like it's anything. :) 

I think part of the problem is that what Quinoa does is kind of complicated, and it's not just "integrate with Wiremock" or "integrate with Hibernate," like some of our other extensions that have a third-party library in the name.

**Comment by melloware** [comment]
True story.  I will close this ticket in favor of the other one...
